services:
    db:
        image: mysql
        container_name: database
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 3307:3307
        volumes:
            - /opt/applications/data_persistence/database/database:/var/lib/mysql
    api:
        build: .
        container_name: api
        environment:
            - SECRET_KEY='123456'
            - SENTRY_DSN=https://1ec59b6f57ba478a9ea2e0c048e1ba4b@o987953.ingest.us.sentry.io/5945041
            - MYSQL_ROOT_HOST=db
            - MYSQL_DATABASE=mysql
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_TCP_PORT=3306
        restart: "on-failure"
        command: ["sh", "./config/run.sh"]
        volumes:
            - .:/application
        depends_on:
            - db
        links:
            - db
        ports:
            - "8000:8000"