services:
    db:
        image: postgres:latest
        container_name: database
        restart: always
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - "5432:5432"
        volumes:
            - /opt/applications/data_persistence/database/database:/var/lib/postgresql/data
    api:
        build: .
        container_name: api
        environment:
            - SECRET_KEY='123456'
            - POSTGRES_HOST=db
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_PORT=5432
        restart: "on-failure"
        command: ["sh", "./config/run.sh"]
        volumes:
            - .:/application
        depends_on:
            - db
        links:
            - db
        ports:
            - "8000:8000"