services:
    db:
        image: postgres:latest
        container_name: database
        env_file: .env
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - /opt/applications/data_persistence/database/database:/var/lib/postgresql/data
    api:
        build: .
        container_name: api
        env_file: .env
        restart: "on-failure"
        command: ["sh", "./config/run.sh"]
        volumes:
            - .:/application
        depends_on:
            - db
        links:
            - db
        ports:
            - "8000:80"